"""Add updated_at field to Channel model

Revision ID: b3a0689ab2dd
Revises: ffd99aecd4ab
Create Date: 2025-01-08 18:57:52.008616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3a0689ab2dd'
down_revision: Union[str, None] = 'ffd99aecd4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('files', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('files', sa.Column('uploaded_by_id', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('files', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'files', 'users', ['uploaded_by_id'], ['id'])
    op.drop_column('files', 'file_url')
    op.drop_column('files', 'uploaded_at')
    op.add_column('reactions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('reactions', 'updated_at')
    op.add_column('files', sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'created_at')
    op.drop_column('files', 'uploaded_by_id')
    op.drop_column('files', 'file_path')
    op.drop_column('channels', 'updated_at')
    # ### end Alembic commands ### 